services:
  - type: web
    name: inventory-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build:render
    staticPublishPath: ./dist/inventory-system
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
    routes:
      # Configuración para SPA - todas las rutas van a index.html
      - type: rewrite
        source: "/(.*)"
        destination: /index.html 